_target_: vibravox.lightning_modules.eben.EBENLightningModule

sample_rate: ${sample_rate}
learning_strategy: "rec_only"
dynamic_loss_balancing: "simple"

defaults:
  - torch_nn_module@generator: eben_generator
  - torch_nn_module@discriminator: eben_discriminator
  - optimizer@generator_optimizer: adam
  - optimizer@discriminator_optimizer: adam
