_target_: vibravox.lightning_modules.eben.EBENLightningModule

defaults:
  - torch_nn_module@generator: eben_generator
  - torch_nn_module@discriminator: melgan_multi_scales
  - optimizer@generator_optimizer: adam
  - optimizer@discriminator_optimizer: adam
