_target_: vibravox.lightning_modules.wav2vec2_for_stp.Wav2Vec2ForSTPLightningModule

sample_rate: ${sample_rate}
push_to_hub_after_testing: True

defaults:
  - optimizer: adam
  - dnn_module@wav2vec2_for_ctc: wav2vec2_for_ctc



