_target_: vibravox.lightning_datamodules.bwe.BWELightningDataModule

sample_rate: ${sample_rate}
dataset_name: "Cnam-LMSSC/vibravox"
subset: "speech_clean"
sensor: "body_conducted.in_ear.rigid_earpiece_microphone"
collate_strategy: "constant_length-2500-ms"
streaming: False
batch_size: 32
num_workers: 16

defaults:
  - data_augmentation: light
  - _self_ # priority is given to bwe.yaml for overrides
