_target_: vibravox.lightning_datamodules.bwe.BWELightningDataModule

sample_rate: ${sample_rate}
dataset_name: "Cnam-LMSSC/vibravox2"
subset: "speech_clean"
sensor: "body_conducted.rigid_in_ear_microphone"
collate_strategy: "constant_length-2500-ms"
streaming: False
batch_size: 32
num_workers: 16

# This is not used in the actual classes, but just for the description and hydra run directory
id: ${lightning_datamodule.sensor}

defaults:
  - data_augmentation: light
  - _self_ # priority is given to bwe.yaml for overrides
