_target_: vibravox.lightning_datamodules.spkv.SPKVLightningDataModule

sample_rate: ${sample_rate}
dataset_name: "Cnam-LMSSC/vibravox"
subset: "speech_clean"
pairs: "mixed_gender" # can also be "same_gender"
sensor_a: "airborne.mouth_headworn.reference_microphone"
sensor_b: "body_conducted.forehead.miniature_accelerometer"
streaming: False
batch_size: 1
num_workers: 16
