_target_: vibravox.lightning_datamodules.spkv.SPKVLightningDataModule

pklfile_path: "configs/lightning_datamodule/spkv_pairs/pairs.pkl"
sample_rate: 16000
dataset_name: "Cnam-LMSSC/vibravox"
subset: "speech_clean"
split: "test"
sensor_a: "airborne.mouth_headworn.reference_microphone"
sensor_b: "body_conducted.forehead.miniature_accelerometer"
streaming: False
batch_size: 1
num_workers: 16
