_target_: vibravox.lightning_datamodules.spkv.SPKVLightningDataModule

sample_rate: ${sample_rate}
dataset_name: "Cnam-LMSSC/vibravox"
subset: "speech_clean"
pairs: "mixed_gender" # can also be "same_gender"
sensor_a: "airborne.mouth_headworn.reference_microphone"
sensor_b: "body_conducted.forehead.miniature_accelerometer"
streaming: False
batch_size: 1
num_workers: 16

# This is not used in the actual classes, but just for the description and hydra run directory
id: ${lightning_datamodule.sensor_a}_${lightning_datamodule.sensor_b}_${lightning_datamodule.dataset_name}_${lightning_datamodule.pairs}
