_target_: vibravox.lightning_datamodules.spkv.SPKVLightningDataModule

sample_rate: 16000
subset: "speech_clean"
split: "test"
pklfile_path: "configs/lightning_datamodule/spkv_pairs/pairs.pkl"
sensor_a: "airborne.mouth_headworn.reference_microphone"
sensor_b: "body_conducted.forehead.miniature_accelerometer"
streaming: False
batch_size: 1
num_workers: 16
