_target_: vibravox.lightning_datamodules.spkv.SPKVLightningDataModule

sample_rate: ${sample_rate}
dataset_name: "Cnam-LMSSC/vibravox"
subset: "speech_clean"
pairs: "mixed_gender" # can also be "same_gender"
sensor_a: "headset_microphone"
sensor_b: "headset_microphone"
streaming: False
batch_size: 1
num_workers: 16

# This is not used in the actual classes, but just for the hydra run directory
id: ${lightning_datamodule.dataset_name}/${lightning_datamodule.subset}/${lightning_datamodule.pairs}/${lightning_datamodule.sensor_a}_vs_${lightning_datamodule.sensor_b}