_target_: vibravox.lightning_datamodules.stp.STPLightningDataModule

sample_rate: ${sample_rate}
dataset_name_principal: "Cnam-LMSSC/vibravox"
#dataset_name_secondary: "Cnam-LMSSC/vibravox-test"
subset: "speech_clean"
sensor: "headset_microphone"
streaming: False
batch_size: 8
num_workers: 16

feature_extractor:
  _target_: transformers.Wav2Vec2FeatureExtractor
  feature_size: 1
  sampling_rate: 16000
  padding_value: 0.0
  do_normalize: True
  return_attention_mask: False

tokenizer:
  _target_: transformers.Wav2Vec2CTCTokenizer.from_pretrained
  pretrained_model_name_or_path: "Cnam-LMSSC/vibravox-phonemes-tokenizer"

# This is not used in the actual classes, but just for the hydra run directory
id: ${lightning_datamodule.sensor}
