### Top-level config file for train.py

# Top-level variables available in all config files
sample_rate: 16000
description: "Baseline: EMA loss balancing with beta=0.99, bs=32, samples_duration=2.5s"

# Hydra configuration
version_base: "1.3"
hydra:
  job:
    chdir: True # change working directory to the job directory
  run:
    dir: "run_outputs/${hydra:runtime.choices.lightning_datamodule}/${lightning_datamodule.sensor}/K/${now:%Y-%m-%d_%H-%M-%S}"


# Composing configs
defaults:
  - lightning_datamodule: bwe # NEEDS TO BE OVERRIDDEN, will also determinate the metrics and the run directory
  - lightning_module: eben # NEEDS TO BE OVERRIDDEN
  - trainer: ddp
  - callbacks: # Dict of callbacks
      #- bwe_checkpoint
      - rich_model_summary
  - logging: tensorboard
  - metrics: ${lightning_datamodule}
  - _self_ # priority is given to train.yaml for overrides
