### Top-level config file for train.py

# Top-level variables available in all config files
sample_rate: 16000
description: "Baseline again: simple LB, no data augmentation but 2/3 update discriminator"

# Hydra configuration
version_base: "1.3"
hydra:
  job:
    chdir: True # change working directory to the job directory
  run:
    dir: "run_outputs/${hydra:runtime.choices.lightning_datamodule}/${lightning_datamodule.sensor}/${now:%Y-%m-%d_%H-%M-%S}"


# Composing configs
defaults:
  - lightning_datamodule: bwe # NEEDS TO BE OVERRIDDEN, will also determinate the metrics and the run directory
  - lightning_module: eben # NEEDS TO BE OVERRIDDEN
  - trainer: ddp
  - callbacks: # Dict of callbacks
      #- bwe_checkpoint
      - rich_model_summary
  - logging: tensorboard
  - metrics: ${lightning_datamodule}
  - _self_ # priority is given to train.yaml for overrides
