_target_: vibravox.torch_modules.dsp.data_augmentation.WaveformDataAugmentation

sample_rate: ${sample_rate}
p_data_augmentation: 0.6
p_speed_perturbation: 0.3
p_pitch_shift: 0.3
p_time_masking: 0.3
speed_perturbation_factors:
  _target_: builtins.tuple
  _args_:
    - [ 0.7, 0.8, 0.85, 0.9, 0.95, 1.05, 1.1, 1.15, 1.2, 1.3]
pitch_shift_steps:
  _target_: builtins.tuple
  _args_:
    - [ -4, -3, -2, -1, 1, 2, 3, 4, 5, 6]
time_masking_percentage:
  _target_: builtins.tuple
  _args_:
    - [ 1, 2, 3, 4, 5, 6, 7, 8]
