_target_: vibravox.torch_modules.dsp.data_augmentation.WaveformDataAugmentation

sample_rate: ${sample_rate}
p_data_augmentation: 0.3
p_speed_perturbation: 0.2
p_pitch_shift: 0.2
p_time_masking: 0.2
speed_perturbation_factors:
  _target_: builtins.tuple
  _args_:
    - [ 0.85, 0.9, 0.95, 1.05, 1.1, 1.15]
pitch_shift_steps:
  _target_: builtins.tuple
  _args_:
    - [ -2, -1, 1, 2]
time_masking_percentage:
  _target_: builtins.tuple
  _args_:
    - [ 1, 2, 3]